### ISSUE TITLE
点击上屏行为闪退

### ISSUE THREAD

**Issue by Wonghitman** [yanhuacuo/rimetool#1]
助手点击上屏行为就闪退了，不知道与我使用的方案是雾凇拼音有无关联，日志见附件
[crash_20240523_151339.dmp](https://github.com/yanhuacuo/rimetool/files/15413093/crash_20240523_151339.dmp)

**Comment by yanhuacuo** [comment]
雾凇方案等下周

**Comment by juezhong** [comment]
我也多次遇到這個問題，我使用的不是霧凇拼音，是 rime 官方的自然碼雙拼方案，是因爲助手自動讀取了我現在的方案導致了閃退嗎，如果是的話爲何使用霧凇拼音方案的朋友也會閃退，以下是我的日誌。
[crash_20240524_092556.dmp](https://github.com/yanhuacuo/rimetool/files/15425883/crash_20240524_092556.dmp)

**Comment by yanhuacuo** [comment]
已适配，仅需作者配合：

https://github.com/iDvel/rime-ice/pull/880

**Comment by yanhuacuo** [comment]
https://github.com/yanhuacuo/rimetool/wiki/%E9%9B%BE%E5%87%87%E6%96%B9%E6%A1%88%E7%9A%84%E5%85%BC%E5%AE%B9%E6%80%A7%E8%AF%B4%E6%98%8E

**Comment by yanhuacuo** [comment]
> 我也多次遇到這個問題，我使用的不是霧凇拼音，是 rime 官方的自然碼雙拼方案，是因爲助手自動讀取了我現在的方案導致了閃退嗎，如果是的話爲何使用霧凇拼音方案的朋友也會閃退，以下是我的日誌。 [crash_20240524_092556.dmp](https://github.com/yanhuacuo/rimetool/files/15425883/crash_20240524_092556.dmp)

哥几个再试试：

https://github.com/yanhuacuo/rimetool/releases/tag/1.1.2
