### ISSUE TITLE
点击上屏行为还是会闪退

### ISSUE THREAD

**Issue by sunny-00001** [yanhuacuo/rimetool#5]
这是报错日志
[crash_20240528_105051.dmp](https://github.com/yanhuacuo/rimetool/files/15463324/crash_20240528_105051.dmp)

**Comment by yanhuacuo** [comment]
刚更了一下，加入了预解析，应该完全可用了，ice-rime 的 文件夹名是「雾凇0528」

**Comment by yanhuacuo** [comment]
https://github.com/yanhuacuo/rimetool/releases/tag/1.1.1

**Comment by sunny-00001** [comment]
还是闪退
[crash_20240528_120505.dmp](https://github.com/yanhuacuo/rimetool/files/15463776/crash_20240528_120505.dmp)

**Comment by yanhuacuo** [comment]
下载使用 v1.1.1 版和同时发布的，最新的配置包，配置包的内部文件夹名称是「雾凇适配包0528」

覆盖，替换，确认雾凇可以打字后，再打开助手，我这边测试正常

https://www.bilibili.com/video/BV14z421e7wE/?spm_id_from=333.999.0.0

另外：

助手本地目录

%LocalAppData%\wubixiaozhu\Rimetool

win+R ，在「运行」窗口中输入上面语句，回车，可以打开，如果还崩，你把整个 Rimetool 的文件夹发上来，我分析一下是不是有什么顽疾。

**Comment by yanhuacuo** [comment]
有另一位群友提交了日志，发现是旧版模式冲突造成的。

你先退出助手，然后把这个 %LocalAppData%\wubixiaozhu\Rimetool 文件夹删了，

使用今天最新的配置包和软件，就完全可用了

**Comment by yanhuacuo** [comment]
再更一波，这次修复了很多问题

1. 支持 ARM 指令集
2. 消除雾凇与薄荷方案的崩溃问题
3. 加入删词后的扫尾工作，不让历史上屏纪录影响删词预期
4. 进一步简化适配，custom文件不强制要求，相关参数自动 fallback

**Comment by sunny-00001** [comment]
更新了最新版，确实有明显提升
1.上屏行为和热键管理都没有闪退了
2.主题杂项中的设置也不卡顿了
发现一个新的问题：切换主题配色失效了
另外每次更改设置都要点击重新部署有些繁琐，能不能自动检测有配置改动立即重新部署或者设置一个阈值，延迟部署

**Comment by yanhuacuo** [comment]
> 更新了最新版，确实有明显提升 1.上屏行为和热键管理都没有闪退了 2.主题杂项中的设置也不卡顿了 发现一个新的问题：切换主题配色失效了 另外每次更改设置都要点击重新部署有些繁琐，能不能自动检测有配置改动立即重新部署或者设置一个阈值，延迟部署

你说的【切换主题配色失效】，是【weasel】系统小托盘菜单中【设置】项的那个？如果是指这里，这是正常的，因为 weasel 现在就是这样的处理方式，每个方案的配色都是独立存在于 xxxx.custom.yaml 中的。

不需要【每一次设置】都要【部署】，而是【每一页选项卡】处理时，做一次部署即可。

**Comment by yanhuacuo** [comment]
> 更新了最新版，确实有明显提升 1.上屏行为和热键管理都没有闪退了 2.主题杂项中的设置也不卡顿了 发现一个新的问题：切换主题配色失效了 另外每次更改设置都要点击重新部署有些繁琐，能不能自动检测有配置改动立即重新部署或者设置一个阈值，延迟部署

rimetool 修改主题没问题，就是正常的预期。方案带上 custom 文件后，小狼毫的设置就改不了该方案的主题了，权限被 custom 文件拿走了，这个设计不是 rimetool 的，是小狼毫最新版本的特性

**Comment by sunny-00001** [comment]
我发现我改了custom文件重新部署也没用，那我要该主题配色应该咋操作呢

**Comment by yanhuacuo** [comment]
> 我发现我改了custom文件重新部署也没用，那我要该主题配色应该咋操作呢

rimetool 的【主题配色】，你改了之后，重新部署也无效？

**Comment by sunny-00001** [comment]
如图所示，更改了rimetool的主题配色并覆盖本地，重新部署无效
![20240529_105039_277](https://github.com/yanhuacuo/rimetool/assets/28869215/b6492a50-cc2e-4185-ab4b-f92cea41adda)
然后我修改了custom文件，重新部署发现无效
![图片](https://github.com/yanhuacuo/rimetool/assets/28869215/b91a9ac6-d969-4df4-a751-52df83e0b973)
我有修改了这里，重新部署，主题色生效，但是没有标签序号
![图片](https://github.com/yanhuacuo/rimetool/assets/28869215/d8f046cb-1eb7-4017-93ae-7fba7716f370)
猜测新版本增加了浅色和深色两种配色方案，我系统设置是深色的，所以更改浅色主题无效
更改了深色主题后标签序号就不见了，奇怪！
![图片](https://github.com/yanhuacuo/rimetool/assets/28869215/8cc45da7-f268-4b11-b9d4-ddf7550fa4f3)
我打开rimetool重新部署后，还是没有标签序号
![图片](https://github.com/yanhuacuo/rimetool/assets/28869215/a1ed23bf-1283-46be-838c-506a2707c90d)

**Comment by yanhuacuo** [comment]
并不是【没有序号】了，而是【你当前使用的主题】已经不知应最新小狼毫的新主题要求了，但是不用担心，rimetool 可以填补这里：

# 你甚至可以给它填加个【候选框阴影色】

![1](https://github.com/yanhuacuo/rimetool/assets/3107994/13ea7eb5-0fad-4b66-9aca-6a4d407a529e)

**Comment by yanhuacuo** [comment]
你说【修改无效】，实际并非如此，而是【你的系统是暗色（深色）模式】，你应勾上【深色锁定】

**Comment by yanhuacuo** [comment]
rimetool 是时时渲染的，你在【配色调整】中看到的当前主题，并不是一个【图片】，而是使用 weasel.yaml 里的参数，即时渲染的，在这里你看不到【序号】，那部署后你也看不到，这是【所见即所得】。

你需要在这个【配色调整】选项页调整一下，参照：

第 2 分 16 秒处：

【中州韵助手：雾凇拼音】 https://www.bilibili.com/video/BV14z421e7wE/?share_source=copy_web&vd_source=37920c8c7678220e3b54da59922b8164

**Comment by sunny-00001** [comment]
谢谢，我明白了
原来是标签序号颜色和背景色相同，所有切换时看不见了
另外下个版本能不能增加自动检测系统配色方案，自动匹配深色或浅色主题
每次切换配色方案默认不勾选深色锁定，有时忘记勾选了

**Comment by yanhuacuo** [comment]
> 谢谢，我明白了 原来是标签序号颜色和背景色相同，所有切换时看不见了 另外下个版本能不能增加自动检测系统配色方案，自动匹配深色或浅色主题 每次切换配色方案默认不勾选深色锁定，有时忘记勾选了

可以，我先记一下。这个程序后面的部分(MacOS 和 Linux)，由98五笔小组其他人来写，我在 windows 下的部分做完了。

试试【主题杂项】的【一键定妆】，这个功能操作一系列参数组合完成的，如果这个也正常，那就完全适配了。

**Comment by sunny-00001** [comment]
主题配色中文字/标签等设置项调色板默认都是白色的
![图片](https://github.com/yanhuacuo/rimetool/assets/28869215/71965bb0-5668-49f5-9b47-2315be1f5595)
1.不能实时显示当前主题该设置的颜色
2.调色板没有吸管，只能手动输入

**Comment by yanhuacuo** [comment]
> 主题配色中文字/标签等设置项调色板默认都是白色的 ![图片](https://private-user-images.githubusercontent.com/28869215/334641812-71965bb0-5668-49f5-9b47-2315be1f5595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTU2MzQsIm5iZiI6MTcxNjk1NTMzNCwicGF0aCI6Ii8yODg2OTIxNS8zMzQ2NDE4MTItNzE5NjViYjAtNTY2OC00OWY1LTliNDctMjMxNWJlMWY1NTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA0MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NjgyNjc0YmQ2OTY0ODY5NDQ2OWY2MTg1MWNjODM2MjgyZWEwMWU0MjFhYWY1ZGFiNWY2NzY2MThjMzIxZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6rftLjcU9UV1_GCYko0qEG2QaYz5ZK1GMt7vCAhoK94) 1.不能实时显示当前主题该设置的颜色 2.调色板没有吸管，只能手动输入

点入，手动拉色相，透明度即可。没有做【取色器】，因为【取色器】取不了【透明度】，初版先这么做吧，后面加上。
