### ISSUE TITLE
存在误报毒情况

### ISSUE THREAD

**Issue by XieyilinMain** [yanhuacuo/rimetool#6]
卡巴斯基等厂商会将rimetool识别为trojan，上传到virustotal后还有其他厂商报毒，建议与安全厂商进行误识别反馈

![图片](https://github.com/yanhuacuo/rimetool/assets/130215387/bf1051bc-6292-4e79-ae2a-83b3a25a1eda)

**Comment by yanhuacuo** [comment]
解决不了，http 请求是拉更新的

**Comment by yanhuacuo** [comment]
一个本地小工具，给杀软添加个例外就好啦，我也没能力写病毒……这个issuses就关啦。
