### ISSUE TITLE
The X11 connection broke

### ISSUE THREAD

**Issue by kkkzh** [yanhuacuo/rimetool#9]
Ubuntu 20.04, NVIDIA Driver 535.146.02
打开时出现以下错误：
2024/06/10 14:15:57.948[Warning][140079471155456]:The X11 connection broke: No error (code 0)
XIO:  fatal IO error 1 (不允许的操作) on X server ":0"
      after 393 requests (393 known processed) with 0 events remaining.

**Comment by yanhuacuo** [comment]
20.04 现在无法兼容了，因为连 Qt6官方发布的 online 包都无法运行在这个版本上了。
软件基于 Qt6.7.1 开发，开发环境是 Debian12，建议在 Ubuntu 最新 lts 版本上使用 rimetool
